### ISSUE TITLE
Samtools index on bam in resmico-bam2feat_TMP

### ISSUE THREAD

**Issue by roachjm-unc** [leylabmpi/ResMiCo#24]
I am getting this error:

[error] Bam file resmico-bam2feat_TMP/IDMG000000AE/NON-HOST/IDMG000000AE_sub_sorted.bam has no index. Please run samtools index to create an index, otherwise I can't be fast

This is a bam that was created by: resmico bam2feat.

The original bam is indexed.

**Comment by roachjm-unc** [comment]
I may have figured this one out.  I think it is due to how I am running multiple samples.

If you have multiple resmico jobs running and they are both using: ./resmico-bam2feat_TMP for temp, though different Taxon and Sample; if one resmico run finishes, will it remove the entire ./resmico-bam2feat_TMP directory (including the temporary files for the unfinished runs) ?

**Comment by nick-youngblut** [comment]
Thanks for posting the issue. 

>If you have multiple resmico jobs running and they are both using: ./resmico-bam2feat_TMP for temp, though different Taxon and Sample; if one resmico run finishes, will it remove the entire ./resmico-bam2feat_TMP directory (including the temporary files for the unfinished runs) ?

By default,  the temporary directory is `resmico-bam2feat_TMP`, as set via `--tmpdir`. The final step of `bam2feat` is to remove the temporary directory, so yes, if you have multiple jobs using the same temporary directory, then this will cause problems. I can add a `--keep` parameter to prevent the removal of the temp directory, or you can use different temp directory names for each job.

**Comment by roachjm-unc** [comment]
No worries.  No need to add a --keep.  I can specify multiple --tmpdir, no problem.  I just didn't realize what was going on and was wondering why the same bam would occasionally fail.

I think I am using this a little bit differently than was intended.  Rather than run ResMiCo on a ton of samples at the same time, I am using it as a step in a larger pipeline.   So each pipeline run is effectively running ResMiCo on a single bam / fna.
