### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'bool'.     resmico evaluate 

### ISSUE THREAD

**Issue by Yunliang81** [leylabmpi/resmico#27]
Hi,

When I run "resmico evaluate", I got an error, which showed "AttributeError: module 'numpy' has no attribute 'bool'. " Please see the following screenshot.

<img width="954" alt="image" src="https://user-images.githubusercontent.com/49252749/217030784-854f9e5b-f17c-47af-8ad0-acf7f61b8db0.png">

Could anyone please help me out?

Thanks,

**Comment by nick-youngblut** [comment]
Which version of numpy are you using? See https://github.com/leylabmpi/resmico/blob/master/environment.yml for the dependency versions required.

**Comment by Yunliang81** [comment]
I re-installed the resmico based on environment.yml. The error disappeared. Thanks.
