### ISSUE TITLE
contig_frac parameter in YAML config file for ResMiCo-SM

### ISSUE THREAD

**Issue by mudamaid62** [leylabmpi/resmico#35]
Hello, and thanks for the awesome tool your research group has developed.

I'm interested in incorporating ResMiCo to my metagenomic pipelines, so I'm following the ResMiCo-SM readme to learn how to use the tool.
The README specifies that "map" parameters are required to run the pipeline with real metagenomic datasets, however, it does not explain what the subparameter contig_frac does. The default values for contig_frac in the repo config.yaml are 1000 and 1500.

How should the parameter contig_frac be used? 

Thanks in advance.

**Comment by nick-youngblut** [comment]
Good catch! The README needs to be updated. 

`contig_frac` is a way to reduce the number of contigs used as a reference during the read mapping steps of the snakemake pipeline. The parameter can be used in 2 ways:

1. If `contig_frac > 1`, it acts as a length cutoff (`contig_length >= contig_frac`).
2. If `contig_frac >= 0 and <=1`, it acts as a subsampling mechanism: what fraction of contigs to randomly subsample and used as a reference for read mapping?

See [the code](https://github.com/leylabmpi/resmico/blob/a6c12e2659510b317a79670c6d2cb2584b91dbe5/ResMiCo-SM/bin/map/Snakefile#L32).
